### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by nicolasmaia** [EXL/AstroSmash#1]
It would be great if you could add your Android apps to F-Droid (https://github.com/EXL/Snooder21 too).

Here's the link: https://f-droid.org/

**Comment by EXL** [comment]
Hi @picsi 
Thanks for the suggestion!

But I'm not sure that these apps comply to this rules:

> Although not ideal, "non-functional" assets (e.g. artwork) may be acceptable under less permissive licenses than functional code - an example would be artwork assets that are licensed only for use with that particular game. In any case though, they must be included under some kind of license, and not be copyright violations.

> Trademarks must not be infringed, and any other legal requirements must be adhered to.

© https://f-droid.org/wiki/page/Inclusion_Policy

**Comment by nicolasmaia** [comment]
Oh, that's too bad! Are you reusing the exact same assets as the original games? 

A simple way to fix the trademark issue would be using a slightly different name like "astrocrash" or "cosmosmash" 😂

**Comment by EXL** [comment]
@picsi 

> Are you reusing the exact same assets as the original games?

True for AstroSmash and also it uses decompiled/reverse-engineering original code.

> A simple way to fix the trademark issue would be using a slightly different name like "astrocrash" or "cosmosmash" 

Yes, Snooder21 has a different name and uses my own graphics assets. Snooder21 can be put to the F-Droid, but I'm ashamed of the poor quality of the code there :D

**Comment by nicolasmaia** [comment]
As long as it's fun and it can be built by F-Droid servers, why not? :)

**Comment by EXL** [comment]
@picsi I'll try to send Snooder21 app to F-Droid when I have free time.

Thank you for attention.

**Comment by EXL** [comment]
Hi @picsi

Snooder 21 was added to the F-Droid repo today.

![screenshot_2017-07-12-19-55-13](https://user-images.githubusercontent.com/232116/28119275-6ecaced2-673e-11e7-9a54-a1a74b1c0dc0.png)

Cheers!

**Comment by nicolasmaia** [comment]
Awesome! Thanks a lot for contributing to the free software community :)
